DROP TABLE VENTASDBC.LI_SUC_DATOS_REPORTE
@

CREATE TABLE VENTASDBC.LI_SUC_DATOS_REPORTE (
    ID_SESION   VARCHAR(100),
    FECHA_HORA_INICIO_TRANSACCION  TIMESTAMP,
    FECHA_HORA_FIN_TRANSACCION TIMESTAMP,
    PASO_FUNCIONAL  VARCHAR(50),
    PASO_FUNCIONAL_DESC  VARCHAR(100),
    TIPO_DOCUMENTO_ID   VARCHAR(100),
    NUMERO_DOCUMENTO    VARCHAR(100),
    NOMBRE_PROD_SELECCIONADO    VARCHAR(100),
    NUMERO_SOLICITUD    VARCHAR(100),
    ID_PROD_OFERTA  VARCHAR(100),
    CUPO_PREAPROBADO    VARCHAR(100),
    COD_SOLICITANTE    VARCHAR(100),
    COD_PRD_SOLICITANTE  VARCHAR(100),
    MONTO_SOLICITADO    BIGINT,
    PLAZO   VARCHAR(100),
    CUOTA_MENSUAL  DOUBLE,
    TASA_MV DOUBLE,
    TASA_NAMV   DOUBLE,
    TASA_EA DOUBLE,
    TASA_MORA   DOUBLE,
    VALOR_SEGURO    DOUBLE,
    CORREO_CLIENTE  VARCHAR(100),
    ACEPTAR_SEGURO  VARCHAR(100),
    DEBITO_AUTOMATICO   VARCHAR(100),
    CTA_DESEMBOLSO  VARCHAR(100),
    CTA_DEBITO  VARCHAR(100),
    ACEPTAR_BENEFICIARIOS   VARCHAR(5),
    BENEFICIARIO_SEGURO VARCHAR(500),
    ACEPTAR_PAGARE  VARCHAR(5),
    RESPUESTA_BIOMETRIA VARCHAR(1000),
    ENVIO_CORREO    VARCHAR(100),
    CODIGO_ASESOR   VARCHAR(100),
    CODIGO_SUCURSAL VARCHAR(100),
    CODIGO_REFERIDO VARCHAR(100),
    CODIGO_ERROR    VARCHAR(100),
    DESCRIPCION_ERROR   VARCHAR(600),
    DURACION    VARCHAR(15),
    OPERACION VARCHAR(100),
    SERVICIO VARCHAR(100),
    TIPO_EXCEPCION VARCHAR(100),
    PASO_A_PASO VARCHAR(2000),
    ID VARCHAR(100),
    PRODUCTO VARCHAR(100),
	COD_SUBPRODUCTO VARCHAR(100),
    NOMBRE_SUBPRODUCTO VARCHAR(100),
    ENTREGA_TARJETA VARCHAR(100),
    RESULTADO_EMISION_INSTANTANEA VARCHAR(100),
    CICLO_PAGO VARCHAR(100),
    SEGMENTO VARCHAR(100),
    SUB_SEGMENTO VARCHAR(100),
    CODIGO_CIUDAD_ENTREGA_TARJETA VARCHAR(100),
    SEGURO_DESEMPLEO VARCHAR(100),
    METODO_DE_FIRMADO VARCHAR(50),
    TIPO_DE_EQUIPO VARCHAR(2)
)
@

CREATE INDEX VENTASDBC.LI_SUC_DATOS_REPORTE_ID_SESION
    ON VENTASDBC.LI_SUC_DATOS_REPORTE
    (ID_SESION ASC)
@

CREATE INDEX VENTASDBC.LI_SUC_DATOS_REPORTE_CODIGO_ERROR
    ON VENTASDBC.LI_SUC_DATOS_REPORTE
    (CODIGO_ERROR ASC)
@

CREATE INDEX VENTASDBC.LI_SUC_DATOS_REPORTE_FECHA_TRANSACCION
    ON VENTASDBC.LI_SUC_DATOS_REPORTE
    (FECHA_HORA_INICIO_TRANSACCION DESC)
@

