DROP  FUNCTION  VENTASDBC.REPORTE_LISUCFN
@

CREATE FUNCTION VENTASDBC.REPORTE_LISUCFN (
        IN PARAM_ID_SESSION VARCHAR(100) 
)
RETURNS VARCHAR(2000)
DETERMINISTIC
READS  SQL DATA
BEGIN
	
	DECLARE VAR_RESPUESTA VARCHAR(2000) DEFAULT '';
	DECLARE VAR_PASO VARCHAR(100) DEFAULT '';
	DECLARE VAR_PASO_B VARCHAR(1) DEFAULT 'N';
	DECLARE VAR_FECHA TIMESTAMP;
	
	FOR CUR_DATA AS (
		SELECT FECHA, PASO  
		FROM VENTASDBC.JSONLI
		WHERE ID_SESSION = PARAM_ID_SESSION 
		ORDER BY FECHA ASC
	) DO
	
		IF (VAR_PASO_B = 'N') THEN
			SET VAR_RESPUESTA = COALESCE(VAR_RESPUESTA,''); 
			SET VAR_FECHA = CUR_DATA.FECHA;
			SET VAR_PASO = CUR_DATA.PASO;
			SET VAR_PASO_B = 'Y';
		ELSE		
			--SET VAR_PASO_B = 'N';
			SET VAR_RESPUESTA = COALESCE(VAR_RESPUESTA,'') || VAR_PASO || ' - ' || CUR_DATA.PASO || ' : Tiempo: ' || (TIMESTAMPDIFF(2, TIMESTAMP(CUR_DATA.FECHA) - TIMESTAMP(VAR_FECHA))) || ' :::::> ';
			SET VAR_FECHA = CUR_DATA.FECHA;
			SET VAR_PASO = CUR_DATA.PASO;
		END IF;	
	END FOR;	
	RETURN VAR_RESPUESTA;
END
@
