DROP  PROCEDURE VENTASDBC.REPORTE_LISUC
@
CREATE PROCEDURE VENTASDBC.REPORTE_LISUC (
        IN FECHA_INI TIMESTAMP,
        IN FECHA_FIN TIMESTAMP
)
LANGUAGE SQL
SPECIFIC VENTASDBC.REPORTE_LISUC
DYNAMIC RESULT SETS 1
P1 : BEGIN
    
 DECLARE CUR_RESPUESTA CURSOR WITH RETURN TO CLIENT FOR
	 SELECT 
	 	ID_SESION, 
		FECHA_HORA_INICIO_TRANSACCION, 
		FECHA_HORA_FIN_TRANSACCION, 
		PASO_FUNCIONAL, 
		PASO_FUNCIONAL_DESC,
	    TIPO_DOCUMENTO_ID,
	    NUMERO_DOCUMENTO,
	    NOMBRE_PROD_SELECCIONADO, 
	    NUMERO_SOLICITUD,
	    ID_PROD_OFERTA, 
	    CUPO_PREAPROBADO,
	    COD_SOLICITANTE,
		COD_PRD_SOLICITANTE,
		MONTO_SOLICITADO,
		PLAZO,
		CUOTA_MENSUAL,
		TASA_MV,
		TASA_NAMV,
		TASA_EA,
		TASA_MORA,
		VALOR_SEGURO,
		CORREO_CLIENTE,
		ACEPTAR_SEGURO,
		DEBITO_AUTOMATICO,
		CTA_DESEMBOLSO,
		CTA_DEBITO,
		ACEPTAR_BENEFICIARIOS,
		BENEFICIARIO_SEGURO,
		ACEPTAR_PAGARE,
		RESPUESTA_BIOMETRIA,
		ENVIO_CORREO,
		CODIGO_ASESOR,
		CODIGO_SUCURSAL,
		CODIGO_REFERIDO,
		CODIGO_ERROR,
		DESCRIPCION_ERROR,
		DURACION,
		OPERACION,
		SERVICIO,
		TIPO_EXCEPCION,
		PASO_A_PASO,
		ID,
		PRODUCTO,
		COD_SUBPRODUCTO,
		NOMBRE_SUBPRODUCTO,
		ENTREGA_TARJETA,
		RESULTADO_EMISION_INSTANTANEA,
		CICLO_PAGO,
		SEGMENTO,
		SUB_SEGMENTO,
		CODIGO_CIUDAD_ENTREGA_TARJETA,
		SEGURO_DESEMPLEO,
		METODO_DE_FIRMADO,
		TIPO_DE_EQUIPO
	FROM VENTASDBC.LI_SUC_DATOS_REPORTE
	WHERE 
	FECHA_HORA_INICIO_TRANSACCION BETWEEN FECHA_INI AND FECHA_FIN
	ORDER BY FECHA_HORA_INICIO_TRANSACCION DESC;
	
	OPEN CUR_RESPUESTA;
        
    
END P1
@



GRANT EXECUTE ON PROCEDURE VENTASDBC.REPORTE_LISUC TO USER LANDINGZB1C
@

GRANT EXECUTE ON PROCEDURE VENTASDBC.REPORTE_LISUC TO USER CNXVDBCP
@

GRANT EXECUTE ON PROCEDURE VENTASDBC.REPORTE_LISUC TO USER DSRENDON
@

GRANT EXECUTE ON PROCEDURE VENTASDBC.REPORTE_LISUC TO USER FLONDONO
@

GRANT EXECUTE ON PROCEDURE VENTASDBC.REPORTE_LISUC TO USER CNXDISEP
@

GRANT EXECUTE ON PROCEDURE VENTASDBC.REPORTE_LISUC TO USER CNXGSSUP
@

