
--DROP TABLE "VENTASDBC"."JSONLI"
--@

CREATE TABLE "VENTASDBC"."JSONLI" (
		"ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
		"FECHA" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		"ID_SESSION" VARCHAR(100), 
		"PASO" VARCHAR(30), 
		"JSON" BLOB(1572864), 
		CONSTRAINT "JSONLI_PK" PRIMARY KEY("ID")
	)
@

CREATE INDEX "VENTASDBC"."JSONLI_ID_SESSION"
	ON "VENTASDBC"."JSONLI"
	("ID_SESSION" ASC)
@

CREATE INDEX "VENTASDBC"."JSONLI_PASO"
	ON "VENTASDBC"."JSONLI"
	("PASO" ASC)
@

CREATE INDEX "VENTASDBC"."JSONLI_SESSION_PASO"
	ON "VENTASDBC"."JSONLI"
	("ID_SESSION" ASC, "PASO" ASC)
@

CREATE INDEX "VENTASDBC"."JSONLI_PASO_SESSION"
	ON "VENTASDBC"."JSONLI"
	("PASO" ASC, "ID_SESSION" ASC)
@


CREATE INDEX "VENTASDBC"."JSONLI_ID"
	ON "VENTASDBC"."JSONLI"
	("ID" ASC)
@

