
--DROP TABLE "VENTASDBC"."LI_SESSION"
--@
CREATE TABLE "VENTASDBC"."LI_SESSION" (
        "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
        "FECHA" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "ID_SESSION" VARCHAR(100)  NOT NULL UNIQUE,
        "USUARIO" VARCHAR(100),
        "ESTADO" VARCHAR(1) DEFAULT '1',
        CONSTRAINT "LI_SESSION_PK" PRIMARY KEY("ID")
)
@


CREATE INDEX "VENTASDBC"."LI_SESSION_ID_SESSION"
	ON "VENTASDBC"."LI_SESSION"
	("ID_SESSION" ASC)
@

CREATE INDEX "VENTASDBC"."LI_SESSION_ESTADO_SESS_USU"
	ON "VENTASDBC"."LI_SESSION"
	("ID_SESSION" ASC, "USUARIO" ASC, "ESTADO")
@
