
--DROP TABLE "VENTASDBC"."LI_AUTENTICACION"
--@
CREATE TABLE "VENTASDBC"."LI_AUTENTICACION" (
        "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER ), 
        "FECHA" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "ID_SESSION" VARCHAR(100), 
        "PASO" VARCHAR(30), 
        "JTI_ACTUAL"  VARCHAR (500) NOT NULL UNIQUE,
        CONSTRAINT "LI_AUTENTICACION_PK" PRIMARY KEY("ID")
)
@

CREATE INDEX "VENTASDBC"."LI_AUTENTICACION_ID_SESSION"
	ON "VENTASDBC"."LI_AUTENTICACION"
	("ID_SESSION" ASC)
@
