--DROP TABLE "VENTASDBC"."JSONLI_HIST"
--@
CREATE TABLE "VENTASDBC"."JSONLI_HIST" (
		"ID" BIGINT NOT NULL , 
		"FECHA" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		"ID_SESSION" VARCHAR(100), 
		"PASO" VARCHAR(30), 
		"JSON" BLOB(1572864), 
		CONSTRAINT "JSONLI_PK" PRIMARY KEY("ID")
	)
@


CREATE INDEX "VENTASDBC"."JSONLI_HIST_ID_SESSION"
	ON "VENTASDBC"."JSONLI_HIST"
	("ID_SESSION" ASC)
@

CREATE INDEX "VENTASDBC"."JSONLI_HIST_PASO"
	ON "VENTASDBC"."JSONLI_HIST"
	("PASO" ASC)
@
CREATE INDEX "VENTASDBC"."JSONLI_HIST_FECHA"
	ON "VENTASDBC"."JSONLI_HIST"
	("FECHA" ASC)
@
CREATE INDEX "VENTASDBC"."JSONLI_FECHA"
	ON "VENTASDBC"."JSONLI"
	("FECHA" ASC)
@
